repos:
    - repo: https://github.com/pycqa/isort
      rev: 5.9.2
      hooks:
          - id: isort
            args: ["--profile", "black"]
            name: isort (python)
          - id: isort
            name: isort (cython)
            types: [cython]
          - id: isort
            name: isort (pyi)
            types: [pyi]
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black
            language_version: python3
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
          - id: mixed-line-ending
            name: line-endings formatting
          - id: trailing-whitespace
            name: trailing whitespaces formatting
            args: [--markdown-linebreak-ext=md]
          - id: end-of-file-fixer
            name: end-of-files formatting
          - id: check-yaml
            name: yaml coding style check (check-yaml)
          - id: check-toml
            name: toml coding style check (check-toml)
    - repo: https://github.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
            name: python coding style check (flake8)
            entry: pflake8
            additional_dependencies: [pyproject-flake8]
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.1.1
      hooks:
          - id: yamlfmt
            args: [--mapping, "4", --sequence, "6", --offset, "4", --preserve-quotes, --implicit_start]
            name: yaml formatting (yamlfmt)
