[tool.black]
line-length = 99

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = "True"
line_length = 99

[tool.flake8]
max-line-length = 99
extend-ignore = "E203,"
per-file-ignores = [
    "*/__init__.py: F401",
]
ignore = [
    "W503",  # line break before binary operator
    "W504",  # line break after binary operator
    "E203",  # https://github.com/psf/black/issues/315
]
